// Auto-generated by build-skins.cjs — do not edit manually
import type { TranslationKey } from '../types';
import locale_en from './en';
import locale_zh_CN from './zh-CN';

export const SUPPORTED_LOCALES = ['en', 'zh-CN'] as const;
export type Language = typeof SUPPORTED_LOCALES[number];

export const STRINGS: Record<Language, Record<TranslationKey, string>> = {
  'en': locale_en,
  'zh-CN': locale_zh_CN,
};
