import type { Language } from '../i18n';

/** HA entity domain → UI label (device card `.state-word`). */
const ZH: Record<string, string> = {
  light: '灯光',
  switch: '开关',
  input_boolean: '开关',
  button: '按钮',
  input_button: '按钮',
  climate: '空调',
  fan: '风扇',
  humidifier: '加湿器',
  water_heater: '热水器',
  cover: '窗帘',
  valve: '阀门',
  media_player: '媒体',
  lock: '门锁',
  alarm_control_panel: '报警',
  vacuum: '扫地机',
  lawn_mower: '割草机',
  camera: '摄像头',
  remote: '遥控',
  sensor: '传感器',
  binary_sensor: '二元传感',
  event: '事件',
  number: '数值',
  select: '选择',
  input_select: '选择',
  input_number: '数值',
  input_text: '文本',
  automation: '自动化',
  script: '脚本',
  scene: '场景',
  update: '更新',
  person: '人员',
  device_tracker: '设备追踪',
  siren: '警笛',
  weather: '天气',
  time: '时间',
  date: '日期',
  datetime: '日期时间',
  text: '文本',
  todo: '待办',
  calendar: '日历',
  notify: '通知',
  conversation: '对话',
  stt: '语音识别',
  tts: '语音合成',
  assist_satellite: '语音助手',
  image: '图片',
  image_processing: '图像处理',
};

const EN: Record<string, string> = {
  light: 'Light',
  switch: 'Switch',
  input_boolean: 'Switch',
  button: 'Button',
  input_button: 'Button',
  climate: 'Climate',
  fan: 'Fan',
  humidifier: 'Humidifier',
  water_heater: 'Water heater',
  cover: 'Cover',
  valve: 'Valve',
  media_player: 'Media',
  lock: 'Lock',
  alarm_control_panel: 'Alarm',
  vacuum: 'Vacuum',
  lawn_mower: 'Mower',
  camera: 'Camera',
  remote: 'Remote',
  sensor: 'Sensor',
  binary_sensor: 'Binary sensor',
  event: 'Event',
  number: 'Number',
  select: 'Select',
  input_select: 'Select',
  input_number: 'Number',
  input_text: 'Text',
  automation: 'Automation',
  script: 'Script',
  scene: 'Scene',
  update: 'Update',
  person: 'Person',
  device_tracker: 'Tracker',
  siren: 'Siren',
  weather: 'Weather',
  time: 'Time',
  date: 'Date',
  datetime: 'Date/time',
  text: 'Text',
  todo: 'To-do',
  calendar: 'Calendar',
};

export function domainLabel(domain: string, language: Language): string {
  const raw = String(domain || '').toLowerCase();
  const map = language === 'zh-CN' ? ZH : EN;
  return map[raw] || domain;
}
