const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const src = 'skins-pro';
const dest = 'dist';

const IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.bmp', '.gif', '.webp'];

function getResizeOptions(filename) {
  const name = path.basename(filename).toLowerCase();
  if (name.startsWith('room-')) {
    return { width: 1200 };
  }
  if (name.startsWith('icon-')) {
    return { width: 300, height: 300, fit: 'inside' };
  }
  if (name.startsWith('avatar')) {
    return { width: 300, height: 300, fit: 'inside' };
  }
  if (name.startsWith('decor')) {
    return { width: 800 };
  }
  if (name.startsWith('base-') || name.startsWith('stage-') || name.startsWith('background.')) {
    return { width: 2560 };
  }
  return { width: 1200 };
}

function getOutputFormat(filename) {
  const name = path.basename(filename).toLowerCase();
  if (name.startsWith('icon-') || name.startsWith('avatar') || name.startsWith('decor')) return 'png';
  return 'jpg';
}

async function processImage(srcPath, destDir) {
  const ext = path.extname(srcPath).toLowerCase();
  if (!IMAGE_EXTENSIONS.includes(ext)) return;

  const opts = getResizeOptions(path.basename(srcPath));
  const fmt = getOutputFormat(path.basename(srcPath));
  const outName = path.basename(srcPath, ext) + '.' + fmt;
  const outPath = path.join(destDir, outName);

  const pipeline = sharp(srcPath);

  if (opts.fit) {
    pipeline.resize({ width: opts.width, height: opts.height, fit: opts.fit, withoutEnlargement: true });
  } else {
    pipeline.resize({ width: opts.width, withoutEnlargement: true });
  }

  if (fmt === 'png') {
    await pipeline.png().toFile(outPath);
  } else {
    await pipeline.jpeg({ quality: 85, mozjpeg: true }).toFile(outPath);
  }
}

const dirs = fs.readdirSync(src, { withFileTypes: true })
  .filter(d => d.isDirectory())
  .map(d => d.name);

(async () => {
  for (const dir of dirs) {
    const srcDir = path.join(src, dir);
    const destDir = path.join(dest, dir);

    fs.mkdirSync(destDir, { recursive: true });

    const entries = fs.readdirSync(srcDir, { withFileTypes: true });
    const jobs = [];

    for (const entry of entries) {
      const srcFile = path.join(srcDir, entry.name);

      if (entry.isFile() && IMAGE_EXTENSIONS.includes(path.extname(entry.name).toLowerCase())) {
        jobs.push(processImage(srcFile, destDir));
      } else if (entry.isFile()) {
        fs.copyFileSync(srcFile, path.join(destDir, entry.name));
      } else if (entry.isDirectory()) {
        fs.cpSync(srcFile, path.join(destDir, entry.name), { recursive: true, force: true });
      }
    }

    await Promise.all(jobs);
  }

  // Generate skin list + strings + icon maps for compile-time injection
  const stringsMap = {};
  const iconMaps = {};
  dirs.forEach(dir => {
    const file = path.join(src, dir, 'strings.json');
    const data = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : {};
    stringsMap[dir] = data;
    iconMaps[dir] = data.icon_map || {};
  });

  fs.writeFileSync(
    path.join('src', 'skins.generated.ts'),
    '// Auto-generated by build-skins.cjs\n' +
    'export const SKINS: readonly string[] = ' + JSON.stringify(dirs) + ';\n' +
    'export const DEFAULT_SKIN: string = ' + JSON.stringify('modern') + ';\n' +
    'export const SKIN_STRINGS: Record<string, any> = ' + JSON.stringify(stringsMap) + ';\n' +
    'export const SKIN_ICON_MAPS: Record<string, Record<string, string>> = ' + JSON.stringify(iconMaps) + ';\n',
  );

  // Generate i18n.generated.ts — auto-discover language files in src/i18n/
  const i18nDir = path.join('src', 'i18n');
  const i18nFiles = fs.readdirSync(i18nDir)
    .filter(f => f.endsWith('.ts') && f !== 'types.ts')
    .sort();
  const localeImports = i18nFiles.map(f => {
    const name = f.replace(/\.ts$/, '');
    const varName = 'locale_' + name.replace(/[^a-zA-Z0-9]/g, '_');
    return `import ${varName} from './i18n/${name}';`;
  }).join('\n');
  const localeEntries = i18nFiles.map(f => {
    const name = f.replace(/\.ts$/, '');
    return `  '${name}': ${'locale_' + name.replace(/[^a-zA-Z0-9]/g, '_')},`;
  }).join('\n');
  const locales = i18nFiles.map(f => `'${f.replace(/\.ts$/, '')}'`).join(', ');
  const buildVersion = new Date().toISOString().replace(/[-:TZ.]/g, '').slice(0, 14);

  fs.writeFileSync(
    path.join('src', 'version.generated.ts'),
    '// Auto-generated by build-skins.cjs — do not edit manually\n' +
    `export const BUILD_VERSION = '${buildVersion}';\n`,
  );

  fs.writeFileSync(
    path.join('src', 'i18n.generated.ts'),
    '// Auto-generated by build-skins.cjs — do not edit manually\n' +
    'import type { TranslationKey } from \'./types\';\n' +
    localeImports + '\n' +
    '\n' +
    'export const SUPPORTED_LOCALES = [' + locales + '] as const;\n' +
    'export type Language = typeof SUPPORTED_LOCALES[number];\n' +
    '\n' +
    'export const STRINGS: Record<Language, Record<TranslationKey, string>> = {\n' +
    localeEntries + '\n' +
    '};\n',
  );

  console.log(`Build complete: ${dirs.length} skin(s) processed, ${i18nFiles.length} locale(s) detected`);
})().catch(err => {
  console.error('Build failed:', err);
  process.exit(1);
});
