import type { DashboardConfig, DeviceConfig, EnvironmentMetricConfig, NavItemConfig, RoomConfig, SceneConfig, TranslationKey, Language } from './types';

export const STRINGS: Record<Language, Record<TranslationKey, string>> = {
  'zh-CN': {
    home: '首页',
    devices: '设备',
    scenes: '场景',
    automations: '自动化',
    rooms: '房间',
    security: '安全',
    energy: '能源',
    environment: '环境信息',
    quickControl: '快捷控制',
    roomSnapshots: '视窗快照',
    modes: '模式',
    todayEnergy: '今日用电',
    maintenance: '维护信息',
    compareYesterday: '较昨日',
    loadingQuote: '加载中',
    offline: '离线',
    noDevices: '暂无设备',
    noScenes: '暂无场景',
    noAutomations: '暂无自动化',
    byArea: '按房间',
    byType: '按类型',
    securityOverview: '摄像头、门锁与布撤防',
    on: '开启',
    off: '关闭',
    open: '打开',
    closed: '关闭',
    solar: '太阳能',
    battery: '电池',
    gas: '燃气',
    water: '用水',
    gridReturn: '返送电网',
  },
  en: {
    home: 'Home',
    devices: 'Devices',
    scenes: 'Scenes',
    automations: 'Automations',
    rooms: 'Rooms',
    security: 'Security',
    energy: 'Energy',
    environment: 'Environment',
    quickControl: 'Quick control',
    roomSnapshots: 'Snapshots',
    modes: 'Modes',
    todayEnergy: 'Energy Today',
    maintenance: 'Maintenance',
    compareYesterday: 'vs yesterday',
    loadingQuote: 'Loading',
    offline: 'Offline',
    noDevices: 'No devices',
    noScenes: 'No scenes',
    noAutomations: 'No automations',
    byArea: 'By area',
    byType: 'By type',
    securityOverview: 'Cameras, locks and arming status',
    on: 'On',
    off: 'Off',
    open: 'Open',
    closed: 'Closed',
    solar: 'Solar',
    battery: 'Battery',
    gas: 'Gas',
    water: 'Water',
    gridReturn: 'Grid Return',
  },
};

export const DEFAULT_ASSETS: Record<string, string> = {
  base: 'base-texture.jpg',
  stage: 'background.jpg',
  theme_css: 'theme.css',
  avatar: 'avatar.png',
  decor: 'decoration.png',
  light: 'icon-light.png',
  switch: 'icon-switch.png',
  button: 'icon-button.png',
  climate: 'icon-ac.png',
  water_heater: 'icon-water_heater.png',
  humidifier: 'icon-humidifier.png',
  fan: 'icon-fan.png',
  speaker: 'icon-speaker.png',
  remote: 'icon-remote.png',
  lock: 'icon-lock.png',
  camera: 'icon-camera.png',
  garden: 'icon-garden-light.png',
  room_living: 'room-living.jpg',
  room_bedroom: 'room-bedroom.jpg',
  room_kitchen: 'room-kitchen.jpg',
  room_garden: 'room-garden.jpg',
};

export const DEFAULT_NAV: NavItemConfig[] = [
  { key: 'home', icon: 'mdi:home' },
  { key: 'devices', icon: 'mdi:devices' },
  { key: 'scenes', icon: 'mdi:palette-swatch' },
  { key: 'automations', icon: 'mdi:robot' },
  { key: 'rooms', icon: 'mdi:door' },
  { key: 'security', icon: 'mdi:shield-home' },
  { key: 'energy', icon: 'mdi:lightning-bolt' },
];

export const DEFAULT_DEVICES: DeviceConfig[] = [
  { entity: 'light.living_room_lights', image: 'light', color: 'yellow' },
  { entity: 'climate.living_room_ac', image: 'climate', color: 'blue', temperature_entity: 'sensor.living_room_temperature' },
  { entity: 'media_player.living_room_speaker', image: 'speaker', color: 'purple' },
  { entity: 'lock.front_door', image: 'lock', color: 'red' },
  { entity: 'light.garden_light_strip', image: 'garden', color: 'green' },
];

export const DEFAULT_ROOMS: RoomConfig[] = [
  { image: 'room_living', info_entity: 'sensor.living_room_summary' },
  { image: 'room_bedroom', info_entity: 'sensor.bedroom_summary' },
  { image: 'room_kitchen', info_entity: 'sensor.kitchen_summary' },
  { image: 'room_garden', info_entity: 'sensor.garden_summary' },
];

export const DEFAULT_SCENES: SceneConfig[] = [
  { entity: 'scene.home_mode', tone: 'morning', icon: 'mdi:home-import-outline', confirm: true },
  { entity: 'scene.good_night', tone: 'night', icon: 'mdi:weather-night', confirm: true },
  { entity: 'scene.welcome_home', tone: 'movie', icon: 'mdi:home-heart', confirm: true },
  { entity: 'scene.away_mode', tone: 'game', icon: 'mdi:exit-run', confirm: true },
];

export const DEFAULT_ENVIRONMENT: EnvironmentMetricConfig[] = [
  { entity: 'sensor.living_room_temperature', icon: 'mdi:thermometer', unit: '°C', variant: 'temp' },
  { entity: 'sensor.living_room_humidity', icon: 'mdi:water-percent', unit: '%', variant: 'hum' },
  { entity: 'sensor.pm25', icon: 'mdi:leaf', unit: '', variant: 'pm' },
];

export const DEFAULT_CONFIG: DashboardConfig = {
  type: 'custom:skins-pro-card',
  language: 'auto',
  resource_pack: {
    skin: 'modern',
    base_path: '__AUTO__',
    assets: DEFAULT_ASSETS,
  },
  weather: {
    entity: 'weather.home',
    temperature_entity: 'sensor.outdoor_temperature',
  },
  info: {
    entity: 'input_text.daily_quote',
  },
  fullscreen: false,
  use_area_pictures: false,
  devices: DEFAULT_DEVICES,
  rooms: DEFAULT_ROOMS,
  scenes: DEFAULT_SCENES,
  environment: DEFAULT_ENVIRONMENT,
  nav: DEFAULT_NAV,
  energy: {
    entity: 'sensor.energy_cost_today',
    unit: 'kWh',
    compare_text_zh: '较昨日',
    compare_text_en: 'vs yesterday',
  },
  home_limits: {
    devices: 5,
    rooms: 4,
    scenes: 6,
    environment: 5,
  },
  home_selection: {
    devices: [],
    rooms: [],
    scenes: [],
    environment: [],
  },
};